### ISSUE TITLE
zearn hack no work

### ISSUE THREAD

**Issue by DevidIsCool** [sleepygoofy/xrtamath-cheat-and-inspect-cheat#1]
it reloads but nothing happen i can send video footage and output commands for it

**Comment by Keeby99** [comment]
dosent work need updated script soon plz

**Comment by sleepygoofy** [comment]
i will try

**Comment by Keeby99** [comment]
thanks i need it

**Comment by sleepygoofy** [comment]
i am so sorry but no one has made any more and node.js does not like so it wont work

**Comment by sleepygoofy** [comment]
.

**Comment by axdlostfrfr** [comment]
is there a new one yet
